service: serverless-node-cron

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs12.x
  profile: serverless-admin
  environment:
    sourceEmailAddress: ${env:SOURCE_EMAIL_ADDRESS}
    destinationEmailAddress: ${env:DESTINATION_EMAIL_ADDRESS}
    api_key: ${env:API_KEY}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "ses:*"
       Resource:
         - "*"

package:
  individually: true

plugins:
  # - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.js   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules

functions:
  dailyReminder:
    handler: ./src/lambdas/dailyReminderHandler.sendDailyReminder
    events:
      # Invoke the Lambda function everyday
      - schedule: rate(1 day)
  weekendReminder:
    handler: ./src/lambdas/weekendReminderHandler.sendWeekendReminder
    events:
      # Invoke the Lambda function every weekend at 1pm US/Eastern Time
       - schedule: cron(30 22 ? * SUN,SAT *)
  handler:
    handler: ./src/lambdas/handler

